language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  # Use PHP 5.4 for coverage reporting.
  include:
    - php: 5.4
      env:
        - secure: "IH/kqLvoz8xjhwreDo9P5jkAFRkQC+2oaFZFVtit7rgqntaQUqYb7cd1+3Y4\nANXpWtmC+OYnrzM+idnRItc7AV/r/Miu0Ki7ZbdxgFa8F+Z9VwMC+17smbiW\nFh2enR1FRHa4yj4WMpPVE8Vk3jD+HUuJbCsQWLW9c77bA0AI4Tg="

  # PHP 5.5 is still in alpha, so ignore build failures.
  allow_failures:
    - php: 5.5

install: composer install --dev --prefer-source
script:  ./vendor/bin/travis-build
