language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "SiOC21wKzpCTYuB45JqEwkbghDCKBGx5q3vlqWKs8n8T421eXrMSQl+AMLRsk2x4btjfktq0I2/6zVpqW4jMofkNvukvSP2BPPppojG+19u/+28+noFeeu0n3CLaxI9vvWlUQUXyr5ry8QG+/SlRfoPlLO68LftHYrlmBUFSSeU="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
