language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "IZakmPKJn80HAQvKuiRctcu1tcgDjkF/qfvpNfDkf0HYPVCmh3rVepLGSEmK6FP4U4geVDTGEeyIqTTQRQUSMrIXDpugYarM0G/hWsckHL1vfKI6jmSfORCJeRYrMSCQVlI8NsPMf7tbS7tPYWx74xBkg0IzM+V0M1Ut74NiIpk="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
