var tree = [["Eloquent",,"",
                [["Fixie",,"",
                [["Handle","Eloquent\/Fixie\/Handle.html","",
                [["Exception","Eloquent\/Fixie\/Handle\/Exception.html","",
                [["ClosedHandleException","Eloquent\/Fixie\/Handle\/Exception\/ClosedHandleException.html"," < Exception",
                [        ]],["EmptyHandleException","Eloquent\/Fixie\/Handle\/Exception\/EmptyHandleException.html"," < Exception",
                [        ]],["IoExceptionInterface","Eloquent\/Fixie\/Handle\/Exception\/IoExceptionInterface.html","",
                [        ]],["ReadException","Eloquent\/Fixie\/Handle\/Exception\/ReadException.html"," < Exception",
                [        ]],["WriteException","Eloquent\/Fixie\/Handle\/Exception\/WriteException.html"," < Exception",
                [        ]]        ]],["AbstractHandle","Eloquent\/Fixie\/Handle\/AbstractHandle.html","",
                [        ]],["HandleFactoryInterface","Eloquent\/Fixie\/Handle\/HandleFactoryInterface.html","",
                [        ]],["HandleInterface","Eloquent\/Fixie\/Handle\/HandleInterface.html","",
                [        ]]        ]],["Reader","Eloquent\/Fixie\/Reader.html","",
                [["FixtureReader","Eloquent\/Fixie\/Reader\/FixtureReader.html","",
                [        ]],["ReadHandle","Eloquent\/Fixie\/Reader\/ReadHandle.html"," < AbstractHandle",
                [        ]],["ReadHandleInterface","Eloquent\/Fixie\/Reader\/ReadHandleInterface.html","",
                [        ]]        ]],["Writer","Eloquent\/Fixie\/Writer.html","",
                [["AbstractWriteHandle","Eloquent\/Fixie\/Writer\/AbstractWriteHandle.html"," < AbstractHandle",
                [        ]],["AlignedCompactFixtureWriteHandle","Eloquent\/Fixie\/Writer\/AlignedCompactFixtureWriteHandle.html"," < AbstractWriteHandle",
                [        ]],["AlignedExpandedFixtureWriteHandle","Eloquent\/Fixie\/Writer\/AlignedExpandedFixtureWriteHandle.html"," < AbstractWriteHandle",
                [        ]],["CompactFixtureWriteHandle","Eloquent\/Fixie\/Writer\/CompactFixtureWriteHandle.html"," < AbstractWriteHandle",
                [        ]],["ExpandedFixtureWriteHandle","Eloquent\/Fixie\/Writer\/ExpandedFixtureWriteHandle.html"," < AbstractWriteHandle",
                [        ]],["FixtureWriter","Eloquent\/Fixie\/Writer\/FixtureWriter.html","",
                [        ]],["SwitchingCompactFixtureWriteHandle","Eloquent\/Fixie\/Writer\/SwitchingCompactFixtureWriteHandle.html"," < AbstractHandle",
                [        ]],["WriteHandleInterface","Eloquent\/Fixie\/Writer\/WriteHandleInterface.html","",
                [        ]]        ]]        ]]        ]]        ]

